### ISSUE TITLE
Package Error

### ISSUE THREAD

**Issue by Creator754915** [Program132/TextGameEngine#1]
Bonsoir,
Les fichier du Moteur de jeu ne son pas **sous forme de package**.
Ce qui veut dire que lorsqu'on installe la librérie et que l'on souhaite coder un jeu on obtient cette erreur:
```
Traceback (most recent call last):
  File "C:\Users\xxx\Ursina Engine Python\TextEngine.py", line 1, in <module>
    from TextGameEngine.src.Models.Circle import Circle
  File "C:\Users\xxx\Ursina Engine Python\TextGameEngine\src\Models\Circle.py", line 2, in <module>
    from src.Models.Point import Point
**ModuleNotFoundError: No module named 'src'**
```

### Ainsi pour régler le problèmes il faut placer dans chaque fichier un fichier Python: **_ _ _init_ _ _.py**
*(avec le petit logo rond, cela montre que c'est un package)*
![image](https://github.com/user-attachments/assets/e1bcc0f1-f6bb-4dd8-9302-99e0b66e1127)

### Suite a cela, nous mettons dans chaque fichier Python le chemin en incluant le package originale:

![image](https://github.com/user-attachments/assets/8a10397b-739c-488a-b659-7cbe64b0d1a7)

Après tout cela, il n'y a plus de problème et le Moteur fonctionne correctement.
Merci, Creator754915

**Comment by Program132** [comment]
Avec le dernier commit ça devrait être fixé
